spring:
  datasource:
    url:  jdbc:postgresql://localhost/msa
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver

# server:
#   servlet-path: /s
# spring:
#   jersey:
#     type: servlet
