spring:
  application:
    name: dao-service
  datasource:
    url: jdbc:postgresql://localhost/msa
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8090/eureka

server:
  port: 8082
security:
  oauth2:
    client:
      client-id: ${GITHUB_CLIENTID}
      client-secret: ${GITHUB_CLIENT_SECRET}
      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://github.com/login/oauth/authorize
      client-authentication-scheme: form
    resource:
      user-info-uri: https://api.github.com/user
      prefer-token-info: false
