server:
  port: 8210

spring:
  application:
    name: DaoService
  output:
    ansi:
      enabled: ALWAYS
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

info:
  name: DaoService

logging:
  file: logfile/dao.log
